exports.addNote = "INSERT INTO NOTE(id, url, timestamp) VALUES (?, ?, NOW())"
exports.patchNote = "INSERT INTO NOTE(id, url, draw_url, timestamp) VALUES (?, ?, ?, NOW())"
exports.getNotes = "SELECT NOTE.idx, NOTE.id, NOTE.url, NOTE.draw_url, NOTE.timestamp, count(MEMO.idx) as memo_length FROM NOTE LEFT JOIN MEMO ON NOTE.idx = MEMO.note_id WHERE id = (?) GROUP BY NOTE.idx"
exports.getNote = "SELECT * FROM NOTE WHERE idx = (?)"
exports.getNoteWithUrl = "SELECT * FROM NOTE WHERE url = (?) AND id = (?)"
// exports.getSharingNotes = "SELECT * FROM NOTE JOIN SHARE ON NOTE.idx = SHARE.note_id WHERE SHARE.send = (?) AND SHARE.state = '사용'"
// exports.getNotes = "SELECT NOTE.idx, NOTE.id, NOTE.url, NOTE.draw_url, NOTE.timestamp, count(MEMO.idx) as memo_length FROM NOTE LEFT JOIN MEMO ON NOTE.idx = MEMO.note_id WHERE id = (?) GROUP BY NOTE.idx"

exports.getSharingNotes = "SELECT SHARE.idx, NOTE.id, NOTE.url, NOTE.draw_url, NOTE.timestamp, SHARE.send, SHARE.receive, SHARE.note_id, SHARE.state, count(MEMO.idx) as memo_length FROM NOTE JOIN SHARE ON NOTE.idx = SHARE.note_id LEFT JOIN MEMO ON NOTE.idx = MEMO.note_id WHERE SHARE.send = (?) AND SHARE.state = '사용' GROUP BY NOTE.idx, SHARE.idx, SHARE.receive"
exports.getSharedNotes = "SELECT SHARE.idx, NOTE.id, NOTE.url, NOTE.draw_url, NOTE.timestamp, SHARE.send, SHARE.receive, SHARE.note_id, SHARE.state, count(MEMO.idx) as memo_length FROM NOTE JOIN SHARE ON NOTE.idx = SHARE.note_id LEFT JOIN MEMO ON NOTE.idx = MEMO.note_id WHERE SHARE.receive = (?) AND SHARE.state = '사용' GROUP BY NOTE.idx, SHARE.idx, SHARE.receive"
// exports.getSharedNotes = "SELECT * FROM NOTE JOIN SHARE ON NOTE.idx = SHARE.note_id WHERE SHARE.receive = (?) AND SHARE.state = '사용'"
exports.getSharedNoteList = "SELECT NOTE.idx, NOTE.id, NOTE.draw_url FROM NOTE JOIN SHARE ON NOTE.idx = SHARE.note_id WHERE SHARE.receive = (?) AND NOTE.url = (?) AND SHARE.state = '사용'"
exports.disconnectSharing = "UPDATE SHARE SET state = '중지' WHERE note_id = (?) AND receive = (?)"
// exports.getSharedNoteList = "SELECT (NOTE.idx, NOTE.id, NOTE.draw_url) FROM NOTE JOIN SHARE ON NOTE.idx = SHARE.note_id WHERE SHARE.receive = (?) AND NOTE.url = (?)"
exports.checkShareUser = "SELECT * FROM SHARE WHERE send = (?) AND receive = (?) AND note_id = (?) AND state = '사용'"
exports.addShareUser = "INSERT INTO SHARE(send, receive, note_id, state) VALUES (?, ?, ?, '사용')"
exports.deleteNote = "DELETE FROM NOTE WHERE idx = (?)"

exports.addDraw = "UPDATE NOTE SET draw_url = (?), timestamp = NOW() WHERE idx = (?)"

exports.addMemo = "INSERT INTO MEMO(note_id, timestamp) VALUES (?, NOW())"
exports.getMemo = "SELECT * FROM MEMO WHERE note_id = (?)"
exports.deleteMemo = "DELETE FROM MEMO WHERE idx = (?)"
exports.patchMemo = "UPDATE MEMO SET content = (?), top_px = (?), left_px = (?), timestamp = NOW() WHERE idx = (?)"
